### ISSUE TITLE
第一节课中，有个细节小错误。

### ISSUE THREAD

**Issue by 0xE1337** [WTFAcademy/WTF-gas-optimization#2]
constant：定义一个常量，需要在部署时进行赋值，且后期不可变更。

immutable：定义一个常量，可以在部署时和 constructor 中进行赋值，且后期不可变更。

这两句话中的“部署”改成“声明”或者“编译期间”是不是更好些。

**Comment by 0xKaso** [comment]
已修改措辞，感谢您的反馈。
